from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

# Persistent history + learning state.
s=s.replace('let stocks=[],edgeFilter="ALL",signalFilter="ALL",previousPage="home",editingHolding=null;',
'''let stocks=[],recHistoryData={},edgeFilter="ALL",signalFilter="ALL",previousPage="home",editingHolding=null;''',1)

old='''function recommendation(s){if(!s)return {label:"WAIT",className:"hold",reason:"Ticker is not yet in the scanner.",horizon:20};const threshold=Number($("#threshold")?.value||75),sh=shortSignal(s),opp=Number(s.opp||0),risk=Number(s.risk||0),conf=Number(s.confidence??50),ann=Number(s.announcementSignal||0),delta=Number(s.delta||0),adjusted=opp+sh.score;if(ann<=-15||opp<40||risk>=75||delta<=-12)return {label:"SELL",className:"sell",reason:`Material deterioration detected. ${sh.text}`,horizon:14};if(adjusted>=threshold&&risk<50&&ann>=0&&conf>=55&&sh.score>-10)return {label:"BUY",className:"buy",reason:`Strong opportunity with acceptable risk/confidence. ${sh.text}`,horizon:30};return {label:"HOLD",className:"hold",reason:`Evidence is not strong enough for BUY or weak enough for SELL. ${sh.text}`,horizon:20}}'''
new='''function learnedSignalAdjustment(s){const learn=recHistoryData?.engineLearning;if(!learn?.active)return 0;const a=learn.signalAdjustments||{};let total=0;if(Number(s.momentum||0)>=65)total+=Number(a.momentum||0);if(Number(s.relative1m||0)>=5||Number(s.relative3m||0)>=8)total+=Number(a.relativeStrength||0);if(Number(s.announcementSignal||0)>=10)total+=Number(a.announcements||0);if(Number(s.globalTrendScore||0)>=12)total+=Number(a.globalTrend||0);const sp=Number(s.shortInterestPct);if(isFinite(sp)&&sp<=2)total+=Number(a.lowShorts||0);if(Number(s.valuation??50)>=60)total+=Number(a.value||0);if(Number(s.volumeRatio||0)>=1.25)total+=Number(a.volume||0);return Math.max(-Number(learn.maxTotalAdjustment||5),Math.min(Number(learn.maxTotalAdjustment||5),total))}
function recommendation(s){if(!s)return {label:"WAIT",className:"hold",reason:"Ticker is not yet in the scanner.",horizon:20};const threshold=Number($("#threshold")?.value||75),sh=shortSignal(s),opp=Number(s.opp||0),risk=Number(s.risk||0),conf=Number(s.confidence??50),ann=Number(s.announcementSignal||0),delta=Number(s.delta||0),learn=learnedSignalAdjustment(s),adjusted=opp+learn;if(ann<=-15||opp<40||risk>=75||delta<=-12)return {label:"SELL",className:"sell",reason:`Material deterioration detected. ${sh.text}`,horizon:14,learn};if(adjusted>=threshold&&risk<50&&ann>=0&&conf>=55&&sh.score>-10)return {label:"BUY",className:"buy",reason:`Strong opportunity with acceptable risk/confidence. ${sh.text}${learn?` Historical signal learning adjusts this setup ${learn>0?"+":""}${learn} points.`:""}`,horizon:30,learn};return {label:"HOLD",className:"hold",reason:`Evidence is not strong enough for BUY or weak enough for SELL. ${sh.text}${learn?` Historical signal learning adjusts this setup ${learn>0?"+":""}${learn} points.`:""}`,horizon:20,learn}}'''
if old not in s: raise SystemExit('recommendation function anchor missing')
s=s.replace(old,new,1)

# Best Opportunity learns modestly from completed calls, but still starts from the final backend opportunity score.
s=s.replace('return opp*.42+val*.18+conf*.18+(100-risk)*.14+Math.max(-15,Math.min(15,rel))*.25+Math.max(-12,Math.min(12,ann))*.2+shortAdj*.45-stretch',
            'return (opp+learnedSignalAdjustment(x))*.42+val*.18+conf*.18+(100-risk)*.14+Math.max(-15,Math.min(15,rel))*.25+Math.max(-12,Math.min(12,ann))*.2+shortAdj*.45-stretch',1)

old_best='''function bestOpportunityHtml(s){const r=recommendation(s),name=(s.name&&s.name!==s.ticker)?s.name:s.ticker,desc=s.description||'Company profile is still being enriched.',sector=[s.sector,s.industry].filter(Boolean).join(' · '),reason=decisionReason(s,r),risk=Number(s.risk||0),val=Number(s.valuation??50),conf=Number(s.confidence??50);return `<div class="hero-company">${name}${sector?` · ${sector}`:''}</div><div class="hero-points"><div class="hero-point good"><b>Why it stands out:</b> ${reason}</div><div class="hero-point good"><b>Value check:</b> Opportunity ${Math.round(Number(s.opp||0))}/100 · Valuation ${Math.round(val)}/100 · Confidence ${Math.round(conf)}/100.</div><div class="hero-point watch"><b>Main risk:</b> Risk ${Math.round(risk)}/100. ${s.riskText||'Watch for deterioration in price action, news, shorts or global themes.'}</div></div><div class="hero-text">${desc}</div>`}'''
new_best='''function investmentPlan(s,r){const price=Number(s.price||0),risk=Number(s.risk||0),opp=Number(s.opp||0);if(!price)return {entry:"—",invalidation:"—",upside:"—"};const entryLo=price*.98,entryHi=price*1.01,stopPct=Math.max(.06,Math.min(.15,.05+risk/100*.12)),upPct=Math.max(.08,Math.min(.30,(opp-55)/100));return {entry:`${money(entryLo)}–${money(entryHi)}`,invalidation:`${money(price*(1-stopPct))} risk-control level`,upside:`${money(price*(1+upPct))} upside case`,review:`${r.horizon} days`}}
function bestOpportunityHtml(s){const r=recommendation(s),name=(s.name&&s.name!==s.ticker)?s.name:s.ticker,desc=s.description||'Company profile is still being enriched.',sector=[s.sector,s.industry].filter(Boolean).join(' · '),reason=decisionReason(s,r),risk=Number(s.risk||0),val=Number(s.valuation??50),conf=Number(s.confidence??50),plan=investmentPlan(s,r);return `<div class="hero-company">${name}${sector?` · ${sector}`:''}</div><div class="hero-points"><div class="hero-point good"><b>Why it stands out:</b> ${reason}</div><div class="hero-point good"><b>Value check:</b> Opportunity ${Math.round(Number(s.opp||0))}/100 · Valuation ${Math.round(val)}/100 · Confidence ${Math.round(conf)}/100.</div><div class="hero-point good"><b>Planning range:</b> Entry ${plan.entry} · ${plan.upside} · review in ${plan.review}.</div><div class="hero-point watch"><b>What invalidates it:</b> ${plan.invalidation}. This is a risk-control guide, not a guaranteed support or price target.</div><div class="hero-point watch"><b>Main risk:</b> Risk ${Math.round(risk)}/100. ${s.riskText||'Watch for deterioration in price action, news, shorts or global themes.'}</div></div><div class="hero-text">${desc}</div>`}'''
if old_best not in s: raise SystemExit('bestOpportunityHtml anchor missing')
s=s.replace(old_best,new_best,1)

old_score='''function renderScorecard(){const rows=stocks.map(s=>({s,co:callOutcome(s)})).filter(x=>x.co).sort((a,b)=>new Date(b.co.startDate)-new Date(a.co.startDate)).slice(0,12);$("#scorecard").innerHTML=rows.length?rows.map(({s,co})=>`<div class="stock"><div class="stock-top"><div class="stock-name"><div class="ticker">${s.ticker}</div><div class="company">${co.label} from ${money(co.startPrice)} · ${co.days}/${co.horizon} days</div></div><div class="action ${co.outcome==="FAIL"?"sell":co.outcome==="SUCCESS"?"buy":"hold"}">${co.outcome}</div></div><div class="thesis">Current ${money(s.price)} · return since call ${pctText(co.ret)}</div></div>`).join(""):`<div class="empty">Calls will appear here once live data loads.</div>`}'''
new_score='''function renderScorecard(){const persistent=recHistoryData?.calls||{},completed=Array.isArray(recHistoryData?.completed)?recHistoryData.completed:[],sum=recHistoryData?.summary||{},learn=recHistoryData?.engineLearning||{};const summaryHtml=`<div class="panel"><div class="panel-title">Permanent recommendation record</div><div class="detail-kpis">${["BUY","HOLD","SELL"].map(k=>{const x=sum[k]||{};return detailKpi(k,`${x.completed||0} completed`,x.successRate>=50?"up":"")+detailKpi(`${k} success`,x.successRate==null?"Not enough data":`${x.successRate}%`) }).join("")}</div><div class="trend-source">Stored in recommendations.json so the history survives phone/browser changes.</div></div><div class="panel"><div class="panel-title">Engine learning</div><p>${learn.active?`ACTIVE · ${learn.completedBuyCalls} completed BUY calls · overall success ${learn.overallBuySuccessRate??"—"}%. Signal weights are now being adjusted conservatively from observed results.`:`COLLECTING DATA · ${learn.completedBuyCalls||0}/12 completed BUY calls required before the engine changes any signal weights.`}</p></div>`;const rows=Object.values(persistent).sort((a,b)=>new Date(b.startDate)-new Date(a.startDate)).slice(0,12);const callsHtml=rows.length?rows.map(co=>{const st=stockOf(co.ticker),ret=Number(co.returnPct);return `<div class="stock"><div class="stock-top"><div class="stock-name"><div class="ticker">${co.ticker}</div><div class="company">${co.label} from ${money(co.startPrice)} · ${co.days||0}/${co.horizon} days</div></div><div class="action ${co.outcome==="FAIL"?"sell":co.outcome==="SUCCESS"?"buy":"hold"}">${co.outcome||"TRACKING"}</div></div><div class="thesis">Current ${money(st?.price??co.currentPrice)} · return since call ${isFinite(ret)?pctText(ret):"—"}</div></div>`}).join(""):`<div class="empty">Permanent calls will appear after the recommendation tracker runs.</div>`;$("#scorecard").innerHTML=summaryHtml+callsHtml}'''
if old_score not in s: raise SystemExit('renderScorecard anchor missing')
s=s.replace(old_score,new_score,1)

old_load='''async function loadData(){const st=$("#liveStatus");st.textContent="Updating live ASX scan…";try{const r=await fetch(`./data.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();stocks=Array.isArray(d.stocks)?d.stocks:[];st.textContent=`LIVE ASX SCAN · ${stocks.length} companies · Updated ${new Date(d.updated).toLocaleString("en-AU")}`;render()}catch(e){st.textContent="Could not load the live ASX scan."}}'''
new_load='''async function loadData(){const st=$("#liveStatus");st.textContent="Updating live ASX scan…";try{const stamp=Date.now(),[r,h]=await Promise.all([fetch(`./data.json?v=${stamp}`,{cache:"no-store"}),fetch(`./recommendations.json?v=${stamp}`,{cache:"no-store"}).catch(()=>null)]);if(!r.ok)throw new Error();const d=await r.json();stocks=Array.isArray(d.stocks)?d.stocks:[];recHistoryData=h&&h.ok?await h.json():{};st.textContent=`LIVE ASX SCAN · ${stocks.length} companies · Updated ${new Date(d.updated).toLocaleString("en-AU")}`;render()}catch(e){st.textContent="Could not load the live ASX scan."}}'''
if old_load not in s: raise SystemExit('loadData anchor missing')
s=s.replace(old_load,new_load,1)

# Use backend short adjustment for display. shortSignal score is display/gating only and is never added again.
s=s.replace('["Short adj.",sh.score]', '["Short adj.",Number(s.shortAdjustment||0)]',1)
s=s.replace('["Global trend",Number(s.globalTrendScore||0)]]', '["Global trend",Number(s.globalTrendScore||0)],["Learned adj.",learnedSignalAdjustment(s)]]',1)

# Make the decision section include an actionable planning framework.
s=s.replace('$("#detailCatalyst").textContent=decisionReason(s,r);', 'const plan=investmentPlan(s,r);$("#detailCatalyst").textContent=decisionReason(s,r)+` Planning: preferred entry ${plan.entry}; ${plan.upside}; ${plan.invalidation}; review in ${plan.review}.`;',1)

s=s.replace('When a BUY/HOLD/SELL signal is first seen, ASX Edge records the price and date on this device. BUY is reviewed after 30 days, HOLD after 20 days and SELL after 14 days. This creates a visible success/failure record instead of letting old calls disappear.',
'''BUY/HOLD/SELL calls are now also written to a permanent recommendation history in the repository after each intraday scan. BUY is reviewed after 30 days, HOLD after 20 days and SELL after 14 days. Signal performance is measured and the engine only begins modest weight adjustments after at least 12 completed BUY calls.''',1)

checks=['adjusted=opp+learn','recommendations.json','Permanent recommendation record','Short adj.",Number(s.shortAdjustment||0)','Planning: preferred entry']
for c in checks:
    if c not in s: raise SystemExit('missing '+c)
p.write_text(s,encoding='utf-8')
print('Trust-engine UI patch applied')
