from pathlib import Path

p=Path('scripts/evidence_research.py')
s=p.read_text(encoding='utf-8')
old='''def pdf_text(url):\n    raw=fetch_bytes(url,35); reader=PdfReader(io.BytesIO(raw)); chunks=[]\n    for page in reader.pages[:MAX_PDF_PAGES]:\n        try: chunks.append(page.extract_text() or "")\n        except Exception: pass\n        if sum(len(x) for x in chunks)>=MAX_TEXT_CHARS: break\n    return "\\n".join(chunks)[:MAX_TEXT_CHARS]\n'''
new='''def resolve_pdf_bytes(url):\n    raw=fetch_bytes(url,35)\n    if raw.startswith(b"%PDF"):\n        return raw, url\n\n    # ASX displayAnnouncement pages are consent wrappers. They expose the\n    # underlying document path in a hidden input named pdfURL. Read that\n    # path rather than treating the HTML wrapper as a PDF.\n    html=raw.decode("utf-8",errors="ignore")\n    m=re.search(r'name=["\\\']pdfURL["\\\'][^>]*value=["\\\']([^"\\\']+)',html,re.I)\n    if not m:\n        m=re.search(r'value=["\\\']([^"\\\']+)["\\\'][^>]*name=["\\\']pdfURL["\\\']',html,re.I)\n    if not m:\n        # Defensive fallback for wrappers containing an absolute direct link.\n        m=re.search(r'https?://(?:announcements\\.)?asx\\.com\\.au/asxpdf/[^"\\\'<> ]+\\.pdf',html,re.I)\n        if m:\n            candidates=[m.group(0)]\n        else:\n            raise ValueError("ASX wrapper did not expose a PDF URL")\n    else:\n        path=m.group(1).replace('&amp;','&')\n        candidates=[]\n        if path.startswith('http'):\n            candidates.append(path)\n        else:\n            candidates.extend([\n                'https://announcements.asx.com.au'+path,\n                'https://www.asx.com.au'+path,\n            ])\n\n    last=None\n    for direct in candidates:\n        try:\n            pdf=fetch_bytes(direct,35)\n            if pdf.startswith(b"%PDF"):\n                return pdf,direct\n            last=f"non-PDF response {pdf[:20]!r}"\n        except Exception as e:\n            last=str(e)\n    raise ValueError("Could not retrieve resolved ASX PDF: "+str(last))\n\ndef pdf_text(url):\n    raw,direct_url=resolve_pdf_bytes(url)\n    reader=PdfReader(io.BytesIO(raw)); chunks=[]\n    for page in reader.pages[:MAX_PDF_PAGES]:\n        try: chunks.append(page.extract_text() or "")\n        except Exception: pass\n        if sum(len(x) for x in chunks)>=MAX_TEXT_CHARS: break\n    text="\\n".join(chunks)[:MAX_TEXT_CHARS]\n    if not text.strip():\n        raise ValueError("PDF contained no extractable text: "+direct_url)\n    return text\n'''
if old not in s:
    raise SystemExit('target pdf_text block not found')
s=s.replace(old,new)
# Do not allow no-document runs to masquerade as valid neutral evidence.
s=s.replace('''    text="\\n".join(combined)\n    evidence={k:find_evidence(text,p) for k,p in RULES.items()} if text else {k:[] for k in RULES}\n''','''    text="\\n".join(combined)\n    if not text.strip():\n        return {"ticker":ticker,"status":"NO_DOCUMENTS","reason":"No ASX disclosure PDFs could be read; evidence score intentionally withheld.","announcementsReviewed":len(anns),"documentsRead":0,"evidenceDocuments":doc_meta,"analysedAt":dt.datetime.now(dt.timezone.utc).isoformat()}\n    evidence={k:find_evidence(text,p) for k,p in RULES.items()}\n''')
p.write_text(s,encoding='utf-8')
print('patched ASX evidence PDF resolver')
